# Lecture 9: Functions #

In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions ##  

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [2]:
def triple(x):
    return 3 * x

In [3]:
triple(3)

9

We can also assign a value to a name, and call the function on the name:

In [4]:
num = 4

In [5]:
triple(num)

12

In [6]:
triple(num * 5)

60

## The Anatomy of a Function ##  
    
```python
def functionname(Arguments, Parameters, Expressions_or_Values, keyword='value'):   
    # Function Body
    return_expression = Parameter * Expression_or_Values + Argument
    
    return return_expression

    # Dead Code
    next_return = "This code will never execute"
    return next_return
    
```

## Functions are Type-Agnostic

If it walks like a duck and quacks like a Duck, it must be a Duck.

In [7]:
triple('ha')

'hahaha'

In [8]:
np.arange(4)

array([0, 1, 2, 3])

Feed the array above into our function `triple` to see what is produced:

In [9]:
triple(np.arange(4))

array([0, 3, 6, 9])

### Discussion ###

- What does the following function do?
- What type of input does it take?
- What type of output does it produce?
- What's a good name for the function?

```python
def f(s):     
      return np.round(s / sum(s) * 100, 2)
```

In [15]:
def percent_of_total(population):
    """
     Name: percent_of_total()
     Description: This will determine the percentage of the total amount for a population
    """
    return np.round(population / sum(population) * 100, 2)

percent_of_total?

Signature: percent_of_total(population)
Docstring:
Name: percent_of_total()
Description: This will determine the percentage of the total amount for a population
File:      /tmp/ipykernel_100/1387425743.py
Type:      function

In [11]:
first_four = make_array(1,2,3,4)
first_four

array([1, 2, 3, 4])

In [12]:
percent_of_total(first_four)

array([ 10.,  20.,  30.,  40.])

In [16]:
percent_of_total(make_array(1, 213, 38))

array([  0.4 ,  84.52,  15.08])

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

In [38]:
import math

def hypotenuse_math(x, y):
    "Determine the Hypotenuse using the Math Module"
    x = abs(x)
    y = abs(y)
    hypot_squared = math.pow(x, 2) + math.pow(y, 2)
    hypot = math.sqrt(hypot_squared)
    return hypot

def hypotenuse_np(x, y):
    "Determine the Hypotenuse using the Numpy Module"
    x = abs(x)
    y = abs(y)
    hypot_squared = np.power(x, 2) + np.power(y, 2)
    hypot = np.sqrt(hypot_squared)
    return hypot

def hypotenuse(x, y):
    "Determine the Hypotenuse using the No Modules"
    x = abs(x)
    y = abs(y)
    hypot_squared = (x ** 2 + y ** 2)
    hypot = hypot_squared ** 0.5
    return hypot

In [34]:
hypotenuse_math(3, 4)

5.0

In [35]:
hypotenuse_np(3, 4)

5.0

In [36]:
hypotenuse(3, 4)

5.0

We could've typed the body all in one line. Do you find this more readable or less readable than the original version?

In [39]:
def hypotenuse_one(x, y):
    "Determine the Hypotenuse using a single line of code?"
    return (x ** 2 + y ** 2) ** 0.5

In [40]:
hypotenuse_one(9, 12)

15.0

### Example: A function that takes the year of birth of a person and produces their age in years. ###

In [52]:
def age(year, month):
    "Given a persons birth month & years calculate their age"
    current_y = 2026
    current_m = 6
    
    if month > current_m:
        age = current_y - year
    else:
        age = current_y - year - 1 
    return age

In [53]:
age(2000, 2)

25

Now add some bells and whistles:  Take person's name and year of birth (two arguments). Produce a sentence that states how old they are.

In [54]:
def name_and_age(name, year, month):
    "Calling a function inside of a function"
    return name + ' is ' + str(age(year, month)) + ' years old.'

In [55]:
name_and_age('Joe', 1942, 12)

'Joe is 84 years old.'

## Apply ##

In [56]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904),
    'Birth Month', make_array(1, 4, 7, 9)
)
ages

Person,Birth Year,Birth Month
Jim,1985,1
Pam,1988,4
Michael,1967,7
Creed,1904,9


In [57]:
# table.apply(function_name, 'Column Names', 'Match the number of Arguments')
ages.apply(age, 'Birth Year', 'Birth Month')

array([ 40,  37,  59, 122])

In [58]:
make_array(
    age(ages.column('Birth Year').item(0), ages.column('Birth Month').item(0)),
    age(ages.column('Birth Year').item(1), ages.column('Birth Month').item(1)),
    age(ages.column('Birth Year').item(2), ages.column('Birth Month').item(2)),
    age(ages.column('Birth Year').item(3), ages.column('Birth Month').item(3))
)

array([ 40,  37,  59, 122])

In [59]:
ages.apply(name_and_age, 'Person', 'Birth Year', 'Birth Month')

array(['Jim is 40 years old.', 'Pam is 37 years old.',
       'Michael is 59 years old.', 'Creed is 122 years old.'],
      dtype='<U24')