In [1]:
from datascience import *
import numpy as np

## Columns of Tables are Arrays ##

In [2]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
2,Chris Paul,PG,Oklahoma City Thunder,38506482
3,Russell Westbrook,PG,Houston Rockets,38506482
4,John Wall,PG,Washington Wizards,38199000
5,Kevin Durant,SF,Brooklyn Nets,38199000


In [3]:
nba.num_rows

528

In [4]:
nba.num_columns

5

In [5]:
nba.labels

('rank', 'name', 'position', 'team', 'salary')

In [6]:
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(5)

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
13,Klay Thompson,SG,Golden State Warriors,32742000
60,Draymond Green,PF,Golden State Warriors,18539130
223,Kevon Looney,PF,Golden State Warriors,4464226
316,Willie Cauley-Stein,C,Golden State Warriors,2177483


In [7]:
warriors.relabeled('salary', '$')

rank,name,position,team,$
1,Stephen Curry,PG,Golden State Warriors,40231758
13,Klay Thompson,SG,Golden State Warriors,32742000
60,Draymond Green,PF,Golden State Warriors,18539130
223,Kevon Looney,PF,Golden State Warriors,4464226
316,Willie Cauley-Stein,C,Golden State Warriors,2177483
332,Jordan Poole,SG,Golden State Warriors,1964760
339,Omari Spellman,PF,Golden State Warriors,1897800
496,Alen Smailagic,PF,Golden State Warriors,898310
497,Eric Paschall,PF,Golden State Warriors,898310
502,Damion Lee,SG,Golden State Warriors,842327


In [8]:
warriors

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
13,Klay Thompson,SG,Golden State Warriors,32742000
60,Draymond Green,PF,Golden State Warriors,18539130
223,Kevon Looney,PF,Golden State Warriors,4464226
316,Willie Cauley-Stein,C,Golden State Warriors,2177483
332,Jordan Poole,SG,Golden State Warriors,1964760
339,Omari Spellman,PF,Golden State Warriors,1897800
496,Alen Smailagic,PF,Golden State Warriors,898310
497,Eric Paschall,PF,Golden State Warriors,898310
502,Damion Lee,SG,Golden State Warriors,842327


In [9]:
warriors = nba.where('team', 'Golden State Warriors').drop('team').relabeled('salary', '$')
warriors.show(3)

rank,name,position,$
1,Stephen Curry,PG,40231758
13,Klay Thompson,SG,32742000
60,Draymond Green,PF,18539130


In [10]:
warriors.select('$')

$
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327


In [13]:
# warriors.select('salary')

In [12]:
type(warriors.select('$'))

datascience.tables.Table

In [14]:
warriors.select(3)

$
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327


In [15]:
warriors.select(3).show(5)

$
40231758
32742000
18539130
4464226
2177483


In [16]:
warriors.column('$')

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,   350189])

In [17]:
warriors.column(3)

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,   350189])

In [18]:
type(warriors.column('$'))

numpy.ndarray

In [19]:
np.average(warriors.column('$'))

8154688.538461538

In [26]:
suns = nba.where('team', 'Phoenix Suns').drop('team').relabeled('salary', '$')
suns

rank,name,position,$
30,Devin Booker,SG,27285000
73,Ricky Rubio,PG,16200000
77,Kelly Oubre Jr.,SF,15625000
135,Deandre Ayton,C,9562920
164,Darrell Arthur,F,7464912
197,Aron Baynes,C,5453280
213,Frank Kaminsky,C,4767000
230,Mikal Bridges,SF,4161000
233,Cameron Johnson,SF,4033440
257,Dario Saric,PF,3481986


In [21]:
np.average(warriors.column('$')) - np.average(suns.column('$'))

2393314.5910931174

In [22]:
np.sum(warriors.column('$')) - np.sum(suns.column('$'))

-3455154

In [23]:
warriors.num_rows

13

In [24]:
suns.num_rows

19

## Ranges ##

In [27]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [28]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [29]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [30]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [33]:
warriors.take(0)

rank,name,position,$
1,Stephen Curry,PG,40231758


In [34]:
warriors.take(0, 1, 2)

rank,name,position,$
1,Stephen Curry,PG,40231758
13,Klay Thompson,SG,32742000
60,Draymond Green,PF,18539130


In [35]:
warriors.take(np.arange(3))

rank,name,position,$
1,Stephen Curry,PG,40231758
13,Klay Thompson,SG,32742000
60,Draymond Green,PF,18539130


In [36]:
np.sum(warriors.take(np.arange(5)).column('$'))

98154597

In [37]:
np.sum(suns.take(np.arange(5)).column('$'))

76137832

# Ways to Create a Table #

## Creating a Table from Scratch ##

In [38]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [39]:
Table()

In [40]:
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste


In [41]:
southside.with_column('Blocks from campus', np.arange(4))

Streets,Blocks from campus
Bancroft,0
Durant,1
Channing,2
Haste,3


In [42]:
southside

Streets
Bancroft
Durant
Channing
Haste


In [43]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

Streets,Blocks from campus
Bancroft,0
Durant,1
Channing,2
Haste,3


In [44]:
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

Streets,Blocks from campus
Bancroft,0
Durant,1
Channing,2
Haste,3


## Reading a Table from a File  ##

In [45]:
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS,ACTUAL AVERAGE,RENT,FOOD,CLOTHES,TAXES,OTHER,STATUS
100-200,139.1,0.19,0.43,0.28,0.001,0.099,POOR
200-300,249.45,0.22,0.47,0.23,0.04,0.04,POOR
300-400,335.66,0.23,0.43,0.18,0.045,0.115,FAIR
400-500,433.82,0.18,0.37,0.15,0.055,0.245,FAIR
500-750,547,0.13,0.31,0.17,0.05,0.34,COMFORTABLE
750-1000,880,0,0.37,0.19,0.08,0.36,COMFORTABLE
1000 and over,1125,0,0.29,0.16,0.045,0.505,WELL-TO-DO


In [46]:
du_bois.column('ACTUAL AVERAGE')

array([  139.1 ,   249.45,   335.66,   433.82,   547.  ,   880.  ,  1125.  ])

In [47]:
du_bois.column('FOOD')

array([ 0.43,  0.47,  0.43,  0.37,  0.31,  0.37,  0.29])

In [48]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

array([  59.813 ,  117.2415,  144.3338,  160.5134,  169.57  ,  325.6   ,
        326.25  ])

In [49]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois.with_column('Food $', food_dollars)

CLASS,ACTUAL AVERAGE,RENT,FOOD,CLOTHES,TAXES,OTHER,STATUS,Food $
100-200,139.1,0.19,0.43,0.28,0.001,0.099,POOR,59.813
200-300,249.45,0.22,0.47,0.23,0.04,0.04,POOR,117.241
300-400,335.66,0.23,0.43,0.18,0.045,0.115,FAIR,144.334
400-500,433.82,0.18,0.37,0.15,0.055,0.245,FAIR,160.513
500-750,547,0.13,0.31,0.17,0.05,0.34,COMFORTABLE,169.57
750-1000,880,0,0.37,0.19,0.08,0.36,COMFORTABLE,325.6
1000 and over,1125,0,0.29,0.16,0.045,0.505,WELL-TO-DO,326.25


In [50]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois = du_bois.with_column('Food $', food_dollars)
du_bois

CLASS,ACTUAL AVERAGE,RENT,FOOD,CLOTHES,TAXES,OTHER,STATUS,Food $
100-200,139.1,0.19,0.43,0.28,0.001,0.099,POOR,59.813
200-300,249.45,0.22,0.47,0.23,0.04,0.04,POOR,117.241
300-400,335.66,0.23,0.43,0.18,0.045,0.115,FAIR,144.334
400-500,433.82,0.18,0.37,0.15,0.055,0.245,FAIR,160.513
500-750,547,0.13,0.31,0.17,0.05,0.34,COMFORTABLE,169.57
750-1000,880,0,0.37,0.19,0.08,0.36,COMFORTABLE,325.6
1000 and over,1125,0,0.29,0.16,0.045,0.505,WELL-TO-DO,326.25


In [51]:
np.max(du_bois.column('Food $'))

326.25

In [52]:
du_bois.with_column(
    'Fraction of well-to-do food $', 
    du_bois.column('Food $') / np.max(du_bois.column('Food $')))

CLASS,ACTUAL AVERAGE,RENT,FOOD,CLOTHES,TAXES,OTHER,STATUS,Food $,Fraction of well-to-do food $
100-200,139.1,0.19,0.43,0.28,0.001,0.099,POOR,59.813,0.183335
200-300,249.45,0.22,0.47,0.23,0.04,0.04,POOR,117.241,0.359361
300-400,335.66,0.23,0.43,0.18,0.045,0.115,FAIR,144.334,0.442402
400-500,433.82,0.18,0.37,0.15,0.055,0.245,FAIR,160.513,0.491995
500-750,547,0.13,0.31,0.17,0.05,0.34,COMFORTABLE,169.57,0.519755
750-1000,880,0,0.37,0.19,0.08,0.36,COMFORTABLE,325.6,0.998008
1000 and over,1125,0,0.29,0.16,0.045,0.505,WELL-TO-DO,326.25,1


## Where Method

In [53]:
nba.where('salary', are.above(10000000))

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
2,Chris Paul,PG,Oklahoma City Thunder,38506482
3,Russell Westbrook,PG,Houston Rockets,38506482
4,John Wall,PG,Washington Wizards,38199000
5,Kevin Durant,SF,Brooklyn Nets,38199000
6,James Harden,SG,Houston Rockets,38199000
7,LeBron James,SF,Los Angeles Lakers,37436858
8,Kyle Lowry,PG,Toronto Raptors,34996296
9,Blake Griffin,PF,Detroit Pistons,34449964
10,Tobias Harris,SF,Philadelphia 76ers,32742000


In [54]:
nba.where('salary', are.between(10000000, 20000000))

rank,name,position,team,salary
53,Terry Rozier,PG,Charlotte Hornets,19894737
54,Aaron Gordon,PF,Orlando Magic,19863636
55,Zach LaVine,PG,Chicago Bulls,19500000
56,Kent Bazemore,SG,Sacramento Kings,19269662
57,Goran Dragic,PG,Miami Heat,19217900
58,Jeff Teague,PG,Minnesota Timberwolves,19000000
59,Evan Turner,SG,Atlanta Hawks,18606556
60,Draymond Green,PF,Golden State Warriors,18539130
61,Tristan Thompson,C,Cleveland Cavaliers,18539130
62,Allen Crabbe,G,Minnesota Timberwolves,18500000


In [55]:
nba.where('position', are.containing('G'))

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
2,Chris Paul,PG,Oklahoma City Thunder,38506482
3,Russell Westbrook,PG,Houston Rockets,38506482
4,John Wall,PG,Washington Wizards,38199000
6,James Harden,SG,Houston Rockets,38199000
8,Kyle Lowry,PG,Toronto Raptors,34996296
13,Klay Thompson,SG,Golden State Warriors,32742000
14,Kemba Walker,PG,Boston Celtics,32742000
16,Mike Conley,PG,Utah Jazz,32511624
17,Kyrie Irving,PG,Brooklyn Nets,31742000


## Print and string formatting

In [56]:
1 + 2
3 + 4

7

In [57]:
print(1 + 2)
print(3 + 4)

3
7


In [58]:
'Go Bears!'

'Go Bears!'

In [59]:
print('Go Bears!')

Go Bears!


In [60]:
cal = 'Berkeley'

In [61]:
'{cal} is great'

'{cal} is great'

In [62]:
f'{cal} is great'

'Berkeley is great'

In [ ]:
print(f'{cal} is great')
print(f'{warriors.column("name").item(0)} is pretty great too')