In [1]:
from datascience import *
import numpy as np

### Why Names?

A cell with arithmetic but no names is difficult to interpret.

In [2]:
# Option 1
40 * 15.00

600.0

In [3]:
40 * 52 * 15.00

31200.0

On January 1, 2022, the CA Minimum Wage for Employers with 26 Employees or More increased to $15/hour.

In [4]:
# Option 2
ca_hourly_minimum_wage = 15.00
hours_per_week = 40
weeks_per_year = 52

In [5]:
hours_per_year = hours_per_week * weeks_per_year

In [6]:
hours_per_year

2080

In [7]:
weekly_wages = hours_per_week * ca_hourly_minimum_wage
weekly_wages

600.0

In [8]:
yearly_wages = hours_per_year * ca_hourly_minimum_wage
yearly_wages

31200.0

## Numbers ##

In [9]:
30

30

In [10]:
10 * 3    # int

30

In [11]:
10 / 3    # float

3.3333333333333335

In [12]:
10 / 2

5.0

In [13]:
10 ** 3

1000

In [14]:
10 ** 0.5

3.1622776601683795

In [15]:
1234567 ** 89

139574185988226216352411677967079384654819840770263154148901015711434587555916221871855053939370772085656915237689603767083349991793713346471091572628494106076146419389211087459209170823939332677859093756734470172351895079430772488109105692648444480028380122417140932569432824316430008740958025053716735421344729410520681559715479472541631321425013768978692403188995380725532383634472359562908542469547971146457062422356845701571795811721146126639734809904577967012608961528997012178537266420111446716001493476975934877110973383995456863730247

In [16]:
10 / 3

3.3333333333333335

In [17]:
75892745.215489247589274985712

75892745.21548925

In [18]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [19]:
(13 ** 0.5) ** 2

12.999999999999998

In [20]:
int(10 / 5)

2

In [21]:
int(10 / 4)

2

In [22]:
float(3)

3.0

In [23]:
6 / 4

1.5

In [24]:
6 / 4000

0.0015

In [25]:
6 / 400000000000000000000000000000000000000000000000000000000

1.5e-56

In [26]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56 

6.0

In [28]:
1.5e56 

1.5e+56

In [29]:
x = 5

In [30]:
2x

SyntaxError: invalid decimal literal (207285602.py, line 1)

In [31]:
2 * x

10

In [32]:
# Tuple
1,234,456

(1, 234, 456)

In [33]:
# List
[1, 234, 456]

[1, 234, 456]

## Strings ##

In [34]:
'Flavor'

'Flavor'

In [35]:
# The line below causes a name error
Flavor

NameError: name 'Flavor' is not defined

In [36]:
"Flavor"

'Flavor'

In [37]:
'Don't always use single quotes'

SyntaxError: unterminated string literal (detected at line 1) (2648065634.py, line 1)

In [38]:
"Don't always use single quotes"

"Don't always use single quotes"

In [39]:
"The main character said, \"Hello World\""

'The main character said, "Hello World"'

In [40]:
'straw' 'berry' # concatenation

'strawberry'

In [41]:
'straw' + 'berry' # concatenation

'strawberry'

In [45]:
'Chris' + 'Paul' # spaces aren't added for you

'ChrisPaul'

In [43]:
'Chris' + ' ' + 'Paul'

'Chris Paul'

In [49]:
x = 'Rio'
y = 'Hondo'
z = 'College'
s = ' '

x + s + y + s + z

'Rio Hondo College'

In [50]:
x y

SyntaxError: invalid syntax (1567273689.py, line 1)

In [52]:
'ha ' * 100

'ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha ha '

In [53]:
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [54]:
'ha' + 10

TypeError: can only concatenate str (not "int") to str

In [55]:
'ha' + str(10)

'ha10'

In [56]:
int('3')

3

In [57]:
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [58]:
int(float('3.0'))

3

In [59]:
dot_oh = '.0'
float('3' + dot_oh)

3.0

## Types ##

In [60]:
type(10)

int

In [61]:
a = 10

In [62]:
type(a)

int

In [63]:
type(4.5)

float

In [64]:
type('abc')

str

In [65]:
type(Table.read_table('nba_salaries.csv'))

datascience.tables.Table

In [66]:
type(True)

bool

In [67]:
abs(-5)

5

In [68]:
type(abs)

builtin_function_or_method

## Arrays ##

* An array is a container that holds elements
* The index of the first element starts at zero
* Arrays can have operations performed on them.


In [69]:
first_four = make_array(1, 2, 3, 4)

In [70]:
first_four

array([1, 2, 3, 4])

In [71]:
first_four * 2

array([2, 4, 6, 8])

In [72]:
first_four ** 2

array([ 1,  4,  9, 16])

In [73]:
first_four + 1

array([2, 3, 4, 5])

In [74]:
first_four / 2

array([ 0.5,  1. ,  1.5,  2. ])

In [75]:
first_four - 2

array([-1,  0,  1,  2])

In [76]:
first_four # array is unchanged, just like when we call show/select/drop on Table

array([1, 2, 3, 4])

In [77]:
next_four = make_array(5, 6, 7, 8)

In [78]:
first_four + next_four

array([ 6,  8, 10, 12])

In [79]:
only_three = make_array(5, 6, 7)

In [80]:
# This line will cause an error 
first_four + only_three

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [84]:
mixed_array = make_array(1, 2.0, '3')
mixed_array

array(['1', '2.0', '3'],
      dtype='<U32')

In [81]:
str_array = make_array('ha', 'he', 'ho')

In [82]:
str_array

array(['ha', 'he', 'ho'],
      dtype='<U2')

In [85]:
str_array * 4

TypeError: The 'out' kwarg is necessary when using the string multiply ufunc directly. Use numpy.strings.multiply to multiply strings without specifying 'out'.

In [86]:
next_four

array([5, 6, 7, 8])

In [87]:
next_four.item(0)

5

In [88]:
next_four.item(1)

6

In [89]:
sum(next_four)

26

In [90]:
np.average(next_four)

6.5

In [91]:
len(next_four)

4

## Columns of Tables are Arrays ##

In [92]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
2,Chris Paul,PG,Oklahoma City Thunder,38506482
3,Russell Westbrook,PG,Houston Rockets,38506482
4,John Wall,PG,Washington Wizards,38199000
5,Kevin Durant,SF,Brooklyn Nets,38199000


In [93]:
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(5)

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
13,Klay Thompson,SG,Golden State Warriors,32742000
60,Draymond Green,PF,Golden State Warriors,18539130
223,Kevon Looney,PF,Golden State Warriors,4464226
316,Willie Cauley-Stein,C,Golden State Warriors,2177483


In [94]:
warriors.select('salary')

salary
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327


In [95]:
type(warriors.select('salary'))

datascience.tables.Table

In [96]:
warriors.column('salary')

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,   350189])

In [97]:
type(warriors.column('salary'))

numpy.ndarray

In [98]:
np.average(warriors.column('salary'))

8154688.538461538

In [99]:
suns = nba.where('team', 'Phoenix Suns')

In [100]:
np.average(warriors.column('salary')) - np.average(suns.column('salary'))

2393314.5910931174

In [101]:
np.sum(warriors.column('salary')) - np.sum(suns.column('salary'))

-3455154

In [102]:
warriors.num_rows

13

In [103]:
suns.num_rows

19